### ISSUE TITLE
Support for multiple images per post

### ISSUE THREAD

**Issue by taw** [madwork/tumblr-sync#1]
Hi,

Many tumblrs like let's say [Steve Argyle's](http://steveargyle.tumblr.com/) contain multiple images per post.

It's easy enough to get them all from API, just replace this:

``` ruby
      doc.xpath("//posts/post/photo-url[@max-width='1280']").map { |url| url.text.strip }
```

with this:

``` ruby
      doc.xpath("//posts/post//photo-url[@max-width='1280']").map { |url| url.text.strip }.uniq
```

(`.uniq` necessary as primary image is listed twice, one as itself, second time as part of photoset together with others).

This fetcthes the right images, unfortunately it also screws up the progress bar, as now number of images > number of posts (well, in this case), so this one like is not a proper pull request :-)

**Comment by madwork** [comment]
Hi @taw,

Nice catch! Tumblr API is evolving or perhaps I completely missed the `photoset`.

Maybe to avoid using unnecessary `uniq`, a cleaner solution would be:

``` ruby
require 'net/http'
require 'nokogiri'
uri_endpoint = URI.parse "http://steveargyle.tumblr.com/api/read?id=116490605653"
response = Net::HTTP.get_response uri_endpoint
doc = Nokogiri::XML.parse response.body
pp doc.xpath("//posts/post/photoset//photo-url[@max-width='1280']").map(&:text)
```

I'll look into your PR soon. Thx! :+1:

This project was a bit abandoned unfortunately by lack of time, but I have a old branch `improve-threading` which is waiting its time!

**Comment by taw** [comment]
1-image posts have just photo, multi-image post have photoset and photo with repeated first image.

The complex part was just getting progress bar to do something sensible, as threads download images, but the total it has is number of posts, not images. 

The PR has test cases, so if you want to clean up the code, just rerun tests and see if it still works.

**Comment by madwork** [comment]
My bad, weird API, photoset is not always there, ok... Deleting the first image seems the best way, right.

Ok about PR I'll do.
